num_inputs = 4
num_hidden_layers = 1
neurons_per_hidden_layer = 6
num_outputs = 2
bias = -1
generation_length = 20
ticks_per_generation = generation_length * 60
population_size = 30
num_food = 50
MAX_ANGLE_CHANGE = 10
mutation_rate = 0.2
crossover_rate = 0.7
