num_inputs = 4
num_hidden_layers = 1
neurons_per_hidden_layer = 6
num_outputs = 2
bias = -1
activation_response = 1
generation_length = 10
ticks_per_generation = generation_length * 60
population_size = 30
num_food = 40
MAX_ANGLE_CHANGE = 360
mutation_rate = 0.2
mutation_power = 0.5
crossover_rate = 0.7
GENS_TO_SKIP = 50
